### ISSUE TITLE
Query names containing the "/" character cause a NotFoundError

### ISSUE THREAD

**Issue by KADOTA-Masaki** [treasure-data/td-client-python#106]
I got an error with the following code.

```python
with tdclient.Client(apikey) as client:
    history = client.history('foo/bar', 0, 10) # saved query name 'foo/bar', contains the '/' character.
```
>NotFoundError: List history failed: {"error":"Path and method do not match any API endpoint","message":"Path and method do not match any API endpoint","text":"Path and method do not match any API endpoint","severity":"error","status_code":404}

And, I noticed that the '/' character in the name is not quoted.

https://github.com/treasure-data/td-client-python/blob/af0acaa04b13004c63795331625eed0647ad1edc/tdclient/util.py#L20

expected: /v3/schedule/history/foo%2Fbar
but got: /v3/schedule/history/foo/bar

https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote
>The optional safe parameter specifies additional ASCII characters that should not be quoted — its default value is '/'.

**Comment by chezou** [comment]
Fixed by #116
