### ISSUE TITLE
How to access the error message when an error occurs

### ISSUE THREAD

**Issue by umranium** [treasure-data/td-client-python#38]
When running queries like this:

```
import tdclient

with tdclient.Client() as td:
    job = td.query("sample_datasets", "SELECT COUNT(1) FROM www_access", type="hive")
    job.wait()
    for row in job.result():
        print(repr(row))
```

If the error occurs in treasure data (for example the query length is longer than 1000000 characters) `job.error()` returns `True`. How do I access the error message? Currently I have to obtain the sql query then run it directly to obtain the error message.

**Comment by yyuu** [comment]
There's a property named `debug` in a job object. You can access to it like the following example.

```py
import tdclient

with tdclient.Client() as td:
    job = td.query("sample_datasets", "SOME MALFORMED QUERY", type="hive")
    job.wait()
    if job.error():
        print(job.debug['stderr'])
        #==> FAILED: ParseException line 1:0 cannot recognize input near 'SOME' 'MALFORMED' 'QUERY'
```

See also: https://docs.treasuredata.com/articles/rest-api#get-v3jobshowjobid

**Comment by umranium** [comment]
Thanks! That worked wonderfully!
