### ISSUE TITLE
Documentation for db errors and return status

### ISSUE THREAD

**Issue by mu-mandayam** [treasure-data/td-client-python#46]
When I instantiate a database query object what methods are available to me? 

For example when I call "job = client.query(…..)" I see job.results() etc. What about error codes or status returns? Is there documentation for the returned status messages and error codes for a tdclient API?

**Comment by chezou** [comment]
We have API doc for the existing error list.
You might get these errors for API request.https://tdclient.readthedocs.io/en/latest/api/misc.html#module-tdclient.errors
https://github.com/treasure-data/td-client-python/blob/master/tdclient/api.py#L507-L519
