### ISSUE TITLE
raises an exception when "retry_post_requests == True"

### ISSUE THREAD

**Issue by k24d** [treasure-data/td-client-python#5]
This code raises an exception when "retry_post_requests == True":

https://github.com/treasure-data/td-client-python/blob/master/tdclient/api.py#L208-L209

Is this expected?

**Comment by yyuu** [comment]
It is expected as I code. I believe it's the as same behaviour as td-client-ruby.

https://github.com/treasure-data/td-client-ruby/blob/1adfad4cc0a15b8ccccff0626c8a709fd91db6dd/lib/td/client/api.rb#L435-L440

How do you think how this should be?

**Comment by k24d** [comment]
td-client-ruby DOES retry, doesn't it?

https://github.com/treasure-data/td-client-ruby/blob/1adfad4cc0a15b8ccccff0626c8a709fd91db6dd/lib/td/client/api.rb#L428

I thought you forgot to add "not" before "self._retry_post_requests".

**Comment by yyuu** [comment]
Ah, I've got what you meant. This is a mistake as you pointed out. I'll fix it soon.

**Comment by yyuu** [comment]
Released v0.1.11 including this fix.

https://pypi.python.org/pypi/td-client/0.1.11
