### ISSUE TITLE
API Documentation by Sphinx

### ISSUE THREAD

**Issue by toru-takahashi** [treasure-data/td-client-python#61]
On TreasureData, Python usage increases.
We'd better have an API doc for td-client-python.
This is useful for support to show a doc instead of showing a code line.

The documentation can be hosted on Github Pages

**Comment by chezou** [comment]
We are planning to build a documentation page and waiting for API reference from API team.

**Comment by chezou** [comment]
Now we have documentation site https://tdclient.readthedocs.io/en/latest/
