### ISSUE TITLE
table.tail() fail: 'API' object has no attribute 'tail'

### ISSUE THREAD

**Issue by hoanghaithanh** [treasure-data/td-client-python#88]
I met the error when I run following code:

`import pytd`
`client = pytd.Client()`
`tables = client.list_tables()`
`tables[0].tail(10)`

The full log error is as follow:

![image](https://user-images.githubusercontent.com/25916024/74999947-55404f80-54a0-11ea-9e46-dc6698ee5b74.png)

**Comment by chezou** [comment]
@hoanghaithanh Thank you for your report. Unfortunately, I couldn't reproduce the error. 

Can you share the version of td-client and pytd?

```
$ pip show td-client
$ pip show pytd
```

**Comment by hrs-hthanh** [comment]
@chezou Hi, You were right. I was using td-client 0.14.0.
Thank you for your information. I will close this issue.

**Comment by hoanghaithanh** [comment]
@chezou Hi, you were right, I was using old version. After I upgraded td-client, the error is no longer appears.
I will close the issue. Thank you and have a nice day.
